apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: web-service-template
  title: Create a New Web Service
  description: Creates a new web service with Crossplane v2 and GitOps
  tags:
    - nodejs
    - crossplane-v2
    - recommended
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Information
      required:
        - name
        - description
      properties:
        name:
          title: Name
          type: string
          description: Unique name for your service (lowercase, hyphens only)
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: What does this service do?
          ui:widget: textarea
    
    - title: Repository Information
      required:
        - owner
      properties:
        owner:
          title: Github Owner
          type: string
          description: GitHub username or organization

  steps:
    - id: fetch-base
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/${{ parameters.owner }}/app-template/tree/main
        copyWithoutTemplating:
          - .github/workflows/deploy.yaml
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          imageTag: 'latest'

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        description: ${{ parameters.description }}
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.name }}
        defaultBranch: main
        repoVisibility: private

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: View Pipeline
        url: ${{ steps['publish'].output.remoteUrl }}/actions